### ISSUE TITLE
Add pleasing mapping from session to websockets

### ISSUE THREAD

**Issue by timofurrer** [neolynx/cirrina#9]
I want to be able to easy send messages to all websocket clients opened by a specific session/user.

**Comment by XayOn** [comment]
https://aiohttp.readthedocs.io/en/latest/faq.html#aiohttp-faq-terminating-websockets

**Comment by XayOn** [comment]
The idea behind this is that the user itself issues a login request against the WS, giving us the opportunity to use the user as a key to a websockets dict.

Another approach I'm using on a project when I need anonymous sockets to be controlled (not exactly anonymous, but not identified client-side) I just assign an id to them and send it to the client, then I can interact with it from other clients.

**Comment by XayOn** [comment]
I'll make a PR tomorrow with this implementation.
